name: Fetch Overleaf PDF

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch: # For manual trigger

jobs:
  fetch-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: overleaf-resume-downloader@v1
        with:
          overleaf_url: 'https://www.overleaf.com/read/674737938151dbe61a23502f' # Replace with your overleaf-url
          github_token: ${{ secrets.GITHUB_TOKEN }}
